### ISSUE TITLE
Component tag is not case-sensitive

### ISSUE THREAD

**Issue by chanpl** [ZettaIO/cachet-client#17]
Hi,

I created a component with tags, it seems all tags are converted to lowercase. Can we support case-sensitive tag?

```
>>> cli.components.create(name="test1", status=1, tags="TAG1,Tag2,tag3")
{'order': 0, 'group_id': 0, 'description': '', 'link': '', 'enabled': True, 'meta': None, 'name': 'test1', 'status': 1, 'updated_at': '2020-07-19 14:31:57', 'created_at': '2020-07-19 14:31:57', 'id': 3574, 'status_name': 'Operational', 'tags': {'tag1': 'TAG1', 'tag2': 'Tag2', 'tag3': 'tag3'}}
>>> cli.components.get(3574)
{'id': 3574, 'name': 'test1', 'description': '', 'link': '', 'status': 1, 'order': 0, 'group_id': 0, 'created_at': '2020-07-19 14:31:57', 'updated_at': '2020-07-19 14:31:57', 'deleted_at': None, 'enabled': True, 'meta': None, 'status_name': 'Operational', 'tags': {'tag1': 'TAG1', 'tag2': 'Tag2', 'tag3': 'tag3'}}
>>> cli.components.get(3574).tags
{'tag3', 'tag2', 'tag1'}
>>> cli.components.get(3574).has_tag("TAG1")
False
>>> cli.components.get(3574).has_tag("tag1")
True
>>>
```

Thanks.

**Comment by einarf** [comment]
As far as I know tags are unique (lower case). `has_tag` should probably ignore case. It's definitely a bit that the tag name is converted to lower case. The tag key is the unique id and the tag value is the display name.

Does this sound reasonable?

**Comment by chanpl** [comment]
Thanks, I am fine if this is a behavior in Cachet.

**Comment by einarf** [comment]
I still want to make some improvements for this, so re-opening as a reminder.

**Comment by einarf** [comment]
Think I will look at this for 3.1.1 as I'm wrapping up a few more smaller things. Right now the most important thing was to get schedules support out.

**Comment by einarf** [comment]
4.0.x is now released with improved tag support
