### ISSUE TITLE
Support "visible" property of component groups

### ISSUE THREAD

**Issue by ccampo133** [ZettaIO/cachet-client#9]
Cachet allows you to set a "visible" flag (bit value, 1 or 0) for component groups, indicating whether the group is visible to the public or not. The functionality is equivalent to the existing "visible" functionality for incident. For component groups however, the feature currently appears to be undocumented, but it definitely is supported by the API.

I'm opening this issue with the hopes of the client allowing this visible flag to be set for component groups during creation and update, and retrieved during any gets.

**Comment by einarf** [comment]
It seems 2.3 doesn't support this (as well as metrics and whatnot), but worst case this will return `False` if not supported by the cachet version, something I think is reasonable.

**Comment by ccampo133** [comment]
Gotcha. I didn't even bother checking the Cachet version I am working against, but it appears to be 2.4.0-dev.

**Comment by einarf** [comment]
2.0.0 on PyPI : https://pypi.org/project/cachet-client/2.0.0/
